# CUB â€” Genmitsu 3018 PRO Desktop (smaller gantry)
serial_port: /dev/cu.usbserial-2130
cnc:
  homing_strategy: xy_hard_limits

working_volume:
  x_min: -300.0
  x_max: 0.0
  y_min: -200.0
  y_max: 0.0
  z_min: -80.0
  z_max: 0.0
